server:
  port: 8888
spring:
  application:
    name: reigster-conter
eureka:
  client:
    register-with-eureka: false #启动时不注册 本来就是注册中心 表示自己是注册中心(单机)
    fetch-registry: false  #不向注册中心拉取数据
    service-url:
      defaultZone: http://localhost:8888/eureka/
  server:
    enable-self-preservation: false #关闭自我保护 测试环境用 生产环境一般不用